// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Badge struct {
	ID          int64
	Nombre      string
	Descripcion string
	RequiredRep int64
}

type Categoria struct {
	ID     int64
	Nombre string
}

type Mensaje struct {
	ID         int64
	SenderID   int64
	ReceiverID int64
	Content    string
}

type Misione struct {
	ID            int64
	Title         string
	Description   string
	RequiredLevel int64
	RewardPoints  int64
}

type Ordene struct {
	ID          int64
	ProductoID  int64
	CompradorID int64
	Estado      string
}

type Producto struct {
	ID          int64
	Nombre      string
	Descripcion string
	Precio      float64
	CategoriaID int64
}

type Review struct {
	ID         int64
	ReviewerID int64
	ReviewedID int64
	Rating     int64
	Comment    string
}

type UserMission struct {
	ID        int64
	UserID    int64
	MissionID int64
	Completed bool
}

type Usuario struct {
	ID         int64
	Nombre     string
	Email      string
	Password   string
	Nivel      int64
	Reputacion int64
}
