// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarBadge = `-- name: ActualizarBadge :one
UPDATE badges
SET nombre = ?,
    descripcion = ?,
    required_rep = ?
WHERE id = ?
RETURNING id, nombre, descripcion, required_rep
`

type ActualizarBadgeParams struct {
	Nombre      string
	Descripcion string
	RequiredRep int64
	ID          int64
}

func (q *Queries) ActualizarBadge(ctx context.Context, arg ActualizarBadgeParams) (Badge, error) {
	row := q.db.QueryRowContext(ctx, actualizarBadge,
		arg.Nombre,
		arg.Descripcion,
		arg.RequiredRep,
		arg.ID,
	)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.RequiredRep,
	)
	return i, err
}

const actualizarCategoria = `-- name: ActualizarCategoria :one
UPDATE categorias
SET nombre = ?
WHERE id = ?
RETURNING id, nombre
`

type ActualizarCategoriaParams struct {
	Nombre string
	ID     int64
}

func (q *Queries) ActualizarCategoria(ctx context.Context, arg ActualizarCategoriaParams) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, actualizarCategoria, arg.Nombre, arg.ID)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const actualizarMensaje = `-- name: ActualizarMensaje :one
UPDATE mensajes
SET sender_id = ?,
    receiver_id = ?,
    content = ?
WHERE id = ?
RETURNING id, sender_id, receiver_id, content
`

type ActualizarMensajeParams struct {
	SenderID   int64
	ReceiverID int64
	Content    string
	ID         int64
}

func (q *Queries) ActualizarMensaje(ctx context.Context, arg ActualizarMensajeParams) (Mensaje, error) {
	row := q.db.QueryRowContext(ctx, actualizarMensaje,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
		arg.ID,
	)
	var i Mensaje
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
	)
	return i, err
}

const actualizarMision = `-- name: ActualizarMision :one
UPDATE misiones
SET title = ?,
    description = ?,
    required_level = ?,
    reward_points = ?
WHERE id = ?
RETURNING id, title, description, required_level, reward_points
`

type ActualizarMisionParams struct {
	Title         string
	Description   string
	RequiredLevel int64
	RewardPoints  int64
	ID            int64
}

func (q *Queries) ActualizarMision(ctx context.Context, arg ActualizarMisionParams) (Misione, error) {
	row := q.db.QueryRowContext(ctx, actualizarMision,
		arg.Title,
		arg.Description,
		arg.RequiredLevel,
		arg.RewardPoints,
		arg.ID,
	)
	var i Misione
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RequiredLevel,
		&i.RewardPoints,
	)
	return i, err
}

const actualizarOrden = `-- name: ActualizarOrden :one
UPDATE ordenes
SET producto_id = ?,
    comprador_id = ?,
    estado = ?
WHERE id = ?
RETURNING id, producto_id, comprador_id, estado
`

type ActualizarOrdenParams struct {
	ProductoID  int64
	CompradorID int64
	Estado      string
	ID          int64
}

func (q *Queries) ActualizarOrden(ctx context.Context, arg ActualizarOrdenParams) (Ordene, error) {
	row := q.db.QueryRowContext(ctx, actualizarOrden,
		arg.ProductoID,
		arg.CompradorID,
		arg.Estado,
		arg.ID,
	)
	var i Ordene
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.CompradorID,
		&i.Estado,
	)
	return i, err
}

const actualizarProducto = `-- name: ActualizarProducto :one
UPDATE productos
SET nombre = ?,
    descripcion = ?,
    precio = ?,
    categoria_id = ?
WHERE id = ?
RETURNING id, nombre, descripcion, precio, categoria_id
`

type ActualizarProductoParams struct {
	Nombre      string
	Descripcion string
	Precio      float64
	CategoriaID int64
	ID          int64
}

func (q *Queries) ActualizarProducto(ctx context.Context, arg ActualizarProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, actualizarProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.CategoriaID,
		arg.ID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.CategoriaID,
	)
	return i, err
}

const actualizarReview = `-- name: ActualizarReview :one
UPDATE reviews
SET reviewer_id = ?,
    reviewed_id = ?,
    rating = ?,
    comment = ?
WHERE id = ?
RETURNING id, reviewer_id, reviewed_id, rating, comment
`

type ActualizarReviewParams struct {
	ReviewerID int64
	ReviewedID int64
	Rating     int64
	Comment    string
	ID         int64
}

func (q *Queries) ActualizarReview(ctx context.Context, arg ActualizarReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, actualizarReview,
		arg.ReviewerID,
		arg.ReviewedID,
		arg.Rating,
		arg.Comment,
		arg.ID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ReviewerID,
		&i.ReviewedID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const actualizarUser = `-- name: ActualizarUser :one
UPDATE usuarios
SET nombre = ?,
    email = ?,
    password = ?,
    nivel = ?,
    reputacion = ?
WHERE id = ?
RETURNING id, nombre, email, password, nivel, reputacion
`

type ActualizarUserParams struct {
	Nombre     string
	Email      string
	Password   string
	Nivel      int64
	Reputacion int64
	ID         int64
}

func (q *Queries) ActualizarUser(ctx context.Context, arg ActualizarUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, actualizarUser,
		arg.Nombre,
		arg.Email,
		arg.Password,
		arg.Nivel,
		arg.Reputacion,
		arg.ID,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Password,
		&i.Nivel,
		&i.Reputacion,
	)
	return i, err
}

const actualizarUserMission = `-- name: ActualizarUserMission :one
UPDATE user_missions
SET user_id = ?,
    mission_id = ?,
    completed = ?
WHERE id = ?
RETURNING id, user_id, mission_id, completed
`

type ActualizarUserMissionParams struct {
	UserID    int64
	MissionID int64
	Completed bool
	ID        int64
}

func (q *Queries) ActualizarUserMission(ctx context.Context, arg ActualizarUserMissionParams) (UserMission, error) {
	row := q.db.QueryRowContext(ctx, actualizarUserMission,
		arg.UserID,
		arg.MissionID,
		arg.Completed,
		arg.ID,
	)
	var i UserMission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Completed,
	)
	return i, err
}

const borrarBadge = `-- name: BorrarBadge :execrows
DELETE FROM badges
WHERE id = ?
`

func (q *Queries) BorrarBadge(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarBadge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarCategoria = `-- name: BorrarCategoria :execrows
DELETE FROM categorias
WHERE id = ?
`

func (q *Queries) BorrarCategoria(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCategoria, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarMensaje = `-- name: BorrarMensaje :execrows
DELETE FROM mensajes
WHERE id = ?
`

func (q *Queries) BorrarMensaje(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarMensaje, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarMision = `-- name: BorrarMision :execrows
DELETE FROM misiones
WHERE id = ?
`

func (q *Queries) BorrarMision(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarMision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarOrden = `-- name: BorrarOrden :execrows
DELETE FROM ordenes
WHERE id = ?
`

func (q *Queries) BorrarOrden(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarOrden, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarProducto = `-- name: BorrarProducto :execrows
DELETE FROM productos
WHERE id = ?
`

func (q *Queries) BorrarProducto(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarProducto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarReview = `-- name: BorrarReview :execrows
DELETE FROM reviews
WHERE id = ?
`

func (q *Queries) BorrarReview(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarUser = `-- name: BorrarUser :execrows
DELETE FROM usuarios
WHERE id = ?
`

func (q *Queries) BorrarUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarUserMission = `-- name: BorrarUserMission :execrows
DELETE FROM user_missions
WHERE id = ?
`

func (q *Queries) BorrarUserMission(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarUserMission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarBadgePorID = `-- name: BuscarBadgePorID :one
SELECT id, nombre, descripcion, required_rep
FROM badges
WHERE id = ?
`

func (q *Queries) BuscarBadgePorID(ctx context.Context, id int64) (Badge, error) {
	row := q.db.QueryRowContext(ctx, buscarBadgePorID, id)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.RequiredRep,
	)
	return i, err
}

const buscarCategoriaPorID = `-- name: BuscarCategoriaPorID :one
SELECT id, nombre FROM categorias WHERE id = ?
`

func (q *Queries) BuscarCategoriaPorID(ctx context.Context, id int64) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, buscarCategoriaPorID, id)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const buscarMensajePorID = `-- name: BuscarMensajePorID :one
SELECT id, sender_id, receiver_id, content
FROM mensajes
WHERE id = ?
`

func (q *Queries) BuscarMensajePorID(ctx context.Context, id int64) (Mensaje, error) {
	row := q.db.QueryRowContext(ctx, buscarMensajePorID, id)
	var i Mensaje
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
	)
	return i, err
}

const buscarMisionPorID = `-- name: BuscarMisionPorID :one
SELECT id, title, description, required_level, reward_points
FROM misiones
WHERE id = ?
`

func (q *Queries) BuscarMisionPorID(ctx context.Context, id int64) (Misione, error) {
	row := q.db.QueryRowContext(ctx, buscarMisionPorID, id)
	var i Misione
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RequiredLevel,
		&i.RewardPoints,
	)
	return i, err
}

const buscarOrdenPorID = `-- name: BuscarOrdenPorID :one
SELECT id, producto_id, comprador_id, estado
FROM ordenes
WHERE id = ?
`

func (q *Queries) BuscarOrdenPorID(ctx context.Context, id int64) (Ordene, error) {
	row := q.db.QueryRowContext(ctx, buscarOrdenPorID, id)
	var i Ordene
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.CompradorID,
		&i.Estado,
	)
	return i, err
}

const buscarProductoPorID = `-- name: BuscarProductoPorID :one
SELECT id, nombre, descripcion, precio, categoria_id
FROM productos
WHERE id = ?
`

func (q *Queries) BuscarProductoPorID(ctx context.Context, id int64) (Producto, error) {
	row := q.db.QueryRowContext(ctx, buscarProductoPorID, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.CategoriaID,
	)
	return i, err
}

const buscarReviewPorID = `-- name: BuscarReviewPorID :one
SELECT id, reviewer_id, reviewed_id, rating, comment
FROM reviews
WHERE id = ?
`

func (q *Queries) BuscarReviewPorID(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRowContext(ctx, buscarReviewPorID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ReviewerID,
		&i.ReviewedID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const buscarUserMissionPorID = `-- name: BuscarUserMissionPorID :one
SELECT id, user_id, mission_id, completed
FROM user_missions
WHERE id = ?
`

func (q *Queries) BuscarUserMissionPorID(ctx context.Context, id int64) (UserMission, error) {
	row := q.db.QueryRowContext(ctx, buscarUserMissionPorID, id)
	var i UserMission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Completed,
	)
	return i, err
}

const buscarUserPorID = `-- name: BuscarUserPorID :one
SELECT id, nombre, email, password, nivel, reputacion
FROM usuarios
WHERE id = ?
`

func (q *Queries) BuscarUserPorID(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, buscarUserPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Password,
		&i.Nivel,
		&i.Reputacion,
	)
	return i, err
}

const crearBadge = `-- name: CrearBadge :one
INSERT INTO badges (nombre, descripcion, required_rep)
VALUES (?, ?, ?)
RETURNING id, nombre, descripcion, required_rep
`

type CrearBadgeParams struct {
	Nombre      string
	Descripcion string
	RequiredRep int64
}

func (q *Queries) CrearBadge(ctx context.Context, arg CrearBadgeParams) (Badge, error) {
	row := q.db.QueryRowContext(ctx, crearBadge, arg.Nombre, arg.Descripcion, arg.RequiredRep)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.RequiredRep,
	)
	return i, err
}

const crearCategoria = `-- name: CrearCategoria :one
INSERT INTO categorias (nombre)
VALUES (?)
RETURNING id, nombre
`

func (q *Queries) CrearCategoria(ctx context.Context, nombre string) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, crearCategoria, nombre)
	var i Categoria
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}

const crearMensaje = `-- name: CrearMensaje :one
INSERT INTO mensajes (sender_id, receiver_id, content)
VALUES (?, ?, ?)
RETURNING id, sender_id, receiver_id, content
`

type CrearMensajeParams struct {
	SenderID   int64
	ReceiverID int64
	Content    string
}

func (q *Queries) CrearMensaje(ctx context.Context, arg CrearMensajeParams) (Mensaje, error) {
	row := q.db.QueryRowContext(ctx, crearMensaje, arg.SenderID, arg.ReceiverID, arg.Content)
	var i Mensaje
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
	)
	return i, err
}

const crearMision = `-- name: CrearMision :one
INSERT INTO misiones (title, description, required_level, reward_points)
VALUES (?, ?, ?, ?)
RETURNING id, title, description, required_level, reward_points
`

type CrearMisionParams struct {
	Title         string
	Description   string
	RequiredLevel int64
	RewardPoints  int64
}

func (q *Queries) CrearMision(ctx context.Context, arg CrearMisionParams) (Misione, error) {
	row := q.db.QueryRowContext(ctx, crearMision,
		arg.Title,
		arg.Description,
		arg.RequiredLevel,
		arg.RewardPoints,
	)
	var i Misione
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RequiredLevel,
		&i.RewardPoints,
	)
	return i, err
}

const crearOrden = `-- name: CrearOrden :one
INSERT INTO ordenes (producto_id, comprador_id, estado)
VALUES (?, ?, ?)
RETURNING id, producto_id, comprador_id, estado
`

type CrearOrdenParams struct {
	ProductoID  int64
	CompradorID int64
	Estado      string
}

func (q *Queries) CrearOrden(ctx context.Context, arg CrearOrdenParams) (Ordene, error) {
	row := q.db.QueryRowContext(ctx, crearOrden, arg.ProductoID, arg.CompradorID, arg.Estado)
	var i Ordene
	err := row.Scan(
		&i.ID,
		&i.ProductoID,
		&i.CompradorID,
		&i.Estado,
	)
	return i, err
}

const crearProducto = `-- name: CrearProducto :one
INSERT INTO productos (nombre, descripcion, precio, categoria_id)
VALUES (?, ?, ?, ?)
RETURNING id, nombre, descripcion, precio, categoria_id
`

type CrearProductoParams struct {
	Nombre      string
	Descripcion string
	Precio      float64
	CategoriaID int64
}

func (q *Queries) CrearProducto(ctx context.Context, arg CrearProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, crearProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Precio,
		arg.CategoriaID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Precio,
		&i.CategoriaID,
	)
	return i, err
}

const crearReview = `-- name: CrearReview :one
INSERT INTO reviews (reviewer_id, reviewed_id, rating, comment)
VALUES (?, ?, ?, ?)
RETURNING id, reviewer_id, reviewed_id, rating, comment
`

type CrearReviewParams struct {
	ReviewerID int64
	ReviewedID int64
	Rating     int64
	Comment    string
}

func (q *Queries) CrearReview(ctx context.Context, arg CrearReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, crearReview,
		arg.ReviewerID,
		arg.ReviewedID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ReviewerID,
		&i.ReviewedID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const crearUser = `-- name: CrearUser :one
INSERT INTO usuarios (nombre, email, password, nivel, reputacion)
VALUES (?, ?, ?, ?, ?)
RETURNING id, nombre, email, password, nivel, reputacion
`

type CrearUserParams struct {
	Nombre     string
	Email      string
	Password   string
	Nivel      int64
	Reputacion int64
}

func (q *Queries) CrearUser(ctx context.Context, arg CrearUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUser,
		arg.Nombre,
		arg.Email,
		arg.Password,
		arg.Nivel,
		arg.Reputacion,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Password,
		&i.Nivel,
		&i.Reputacion,
	)
	return i, err
}

const crearUserMission = `-- name: CrearUserMission :one
INSERT INTO user_missions (user_id, mission_id, completed)
VALUES (?, ?, ?)
RETURNING id, user_id, mission_id, completed
`

type CrearUserMissionParams struct {
	UserID    int64
	MissionID int64
	Completed bool
}

func (q *Queries) CrearUserMission(ctx context.Context, arg CrearUserMissionParams) (UserMission, error) {
	row := q.db.QueryRowContext(ctx, crearUserMission, arg.UserID, arg.MissionID, arg.Completed)
	var i UserMission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.Completed,
	)
	return i, err
}

const listarBadges = `-- name: ListarBadges :many

SELECT id, nombre, descripcion, required_rep
FROM badges
`

// ==========================================
// BADGES
// ==========================================
func (q *Queries) ListarBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.QueryContext(ctx, listarBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.RequiredRep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCategorias = `-- name: ListarCategorias :many
SELECT id, nombre
FROM categorias
SELECT id, nombre FROM categorias
`

// Modulo 2
// ==========================================
// categorias
// ==========================================
func (q *Queries) ListarCategorias(ctx context.Context) ([]Categoria, error) {
	rows, err := q.db.QueryContext(ctx, listarCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categoria
	for rows.Next() {
		var i Categoria
		if err := rows.Scan(&i.ID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMensajes = `-- name: ListarMensajes :many

SELECT id, sender_id, receiver_id, content
FROM mensajes
`

// ==========================================
// MENSAJES
// ==========================================
func (q *Queries) ListarMensajes(ctx context.Context) ([]Mensaje, error) {
	rows, err := q.db.QueryContext(ctx, listarMensajes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mensaje
	for rows.Next() {
		var i Mensaje
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMissions = `-- name: ListarMissions :many



SELECT id, title, description, required_level, reward_points
FROM misiones
`

// Modulo 3
// ==========================================
// MISSIONS
// ==========================================
func (q *Queries) ListarMissions(ctx context.Context) ([]Misione, error) {
	rows, err := q.db.QueryContext(ctx, listarMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Misione
	for rows.Next() {
		var i Misione
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.RequiredLevel,
			&i.RewardPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarOrdenes = `-- name: ListarOrdenes :many

SELECT id, producto_id, comprador_id, estado
FROM ordenes
`

// ==========================================
// ORDENES
// ==========================================
func (q *Queries) ListarOrdenes(ctx context.Context) ([]Ordene, error) {
	rows, err := q.db.QueryContext(ctx, listarOrdenes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ordene
	for rows.Next() {
		var i Ordene
		if err := rows.Scan(
			&i.ID,
			&i.ProductoID,
			&i.CompradorID,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarProductos = `-- name: ListarProductos :many

SELECT id, nombre, descripcion, precio, categoria_id
FROM productos
`

// ==========================================
// PRODUCTOS
// ==========================================
func (q *Queries) ListarProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listarProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Precio,
			&i.CategoriaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarReviews = `-- name: ListarReviews :many

SELECT id, reviewer_id, reviewed_id, rating, comment
FROM reviews
`

// ==========================================
// REVIEWS
// ==========================================
func (q *Queries) ListarReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listarReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ReviewerID,
			&i.ReviewedID,
			&i.Rating,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUserMissions = `-- name: ListarUserMissions :many

SELECT id, user_id, mission_id, completed
FROM user_missions
`

// ==========================================
// USER MISSIONS
// ==========================================
func (q *Queries) ListarUserMissions(ctx context.Context) ([]UserMission, error) {
	rows, err := q.db.QueryContext(ctx, listarUserMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMission
	for rows.Next() {
		var i UserMission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MissionID,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsers = `-- name: ListarUsers :many

SELECT id, nombre, email, password, nivel, reputacion
FROM usuarios
`

// Modulo 2
// ==========================================
// USERS
// ==========================================
func (q *Queries) ListarUsers(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listarUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Email,
			&i.Password,
			&i.Nivel,
			&i.Reputacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
